"use client";

import Brand from "@/components/Brand";
import { useLocale } from "@/components/LocaleProvider";
import { ButtonLink } from "@/components/ui/Button";
import type { Locale } from "@/lib/i18n";

type PolicyCopy = {
  eyebrow: string;
  title: string;
  sections: Array<{ title: string; paragraphs: string[] }>;
  notice: string;
  back: string;
};

const COPY: Record<Locale, PolicyCopy> = {
  ko: {
    eyebrow: "서비스 안내",
    title: "AI 분석과 데이터 처리 안내",
    sections: [
      {
        title: "생성형 AI 사용",
        paragraphs: [
          "우사기는 사용자가 직접 입력하거나 업로드한 대화를 생성형 AI로 구조화하고, 대화 패턴에 대한 요약과 참고 의견을 제공합니다.",
          "모든 결과 화면에는 AI가 생성한 결과임을 확인할 수 있는 라벨을 표시합니다.",
        ],
      },
      {
        title: "결과의 한계",
        paragraphs: [
          "우사기는 상대방의 실제 감정, 의도, 호감, 성격, 성적 지향 또는 관계의 진위를 확인하거나 보장하지 않습니다.",
          "결과는 확인 가능한 메시지 수, 질문, 대화 흐름 등의 패턴을 바탕으로 만든 참고 자료이며 의료·법률·금융·심리 진단이나 전문 상담을 대체하지 않습니다.",
        ],
      },
      {
        title: "대화와 개인정보",
        paragraphs: [
          "본인에게 이용 권한이 있는 대화만 입력해야 하며, 주민등록번호, 전화번호, 주소, 계좌번호, 건강 정보 등 민감한 개인정보는 가린 뒤 업로드해야 합니다.",
          "입력값과 결과는 현재 브라우저 세션에 임시 저장될 수 있습니다. 동일 요청의 중복 비용을 줄이기 위해 분석 결과가 서버에 제한된 시간 동안 임시 캐시될 수 있습니다.",
        ],
      },
      {
        title: "서비스 범위",
        paragraphs: [
          "우사기는 대화 패턴 분석 기능을 앱 안에서 완결적으로 제공합니다. 금융·투자 자문, 의료 진단, 도박, 가상자산 거래 또는 외부 앱 설치 유도 기능을 제공하지 않습니다.",
        ],
      },
    ],
    notice: "서비스를 이용하면 위 내용을 확인한 것으로 봅니다. 중요한 관계 판단에서는 AI 결과보다 실제 대화와 당사자 간의 직접적인 소통을 우선해 주세요.",
    back: "홈으로 돌아가기",
  },
  en: {
    eyebrow: "Service notice",
    title: "AI analysis and data handling",
    sections: [
      {
        title: "Use of generative AI",
        paragraphs: [
          "Usagi uses generative AI to structure conversations that you paste or upload and to provide summaries and reference opinions about visible conversation patterns.",
          "Every result screen includes a label indicating that the content was generated by AI.",
        ],
      },
      {
        title: "Limits of the result",
        paragraphs: [
          "Usagi cannot verify or guarantee another person's actual feelings, intent, attraction, personality, sexual orientation, or the true nature of a relationship.",
          "Results are reference material based on observable patterns such as message counts, questions, and conversation flow. They do not replace medical, legal, financial, psychological, or other professional advice.",
        ],
      },
      {
        title: "Chats and personal information",
        paragraphs: [
          "Only submit conversations you are permitted to use. Hide sensitive information such as identification numbers, phone numbers, addresses, account numbers, and health information before uploading.",
          "Inputs and results may be stored temporarily in the current browser session. To reduce duplicate processing costs, analysis results may also be cached on the server for a limited time.",
        ],
      },
      {
        title: "Service scope",
        paragraphs: [
          "Usagi provides conversation-pattern analysis within the app. It does not provide financial or investment advice, medical diagnosis, gambling, crypto trading, or prompts to install another app.",
        ],
      },
    ],
    notice: "By using the service, you acknowledge the information above. For important relationship decisions, prioritize direct communication and the real conversation over an AI-generated result.",
    back: "Back to home",
  },
  ja: {
    eyebrow: "サービス案内",
    title: "AI分析とデータ処理について",
    sections: [
      {
        title: "生成AIの利用",
        paragraphs: [
          "ウサギは、ユーザーが入力またはアップロードした会話を生成AIで構造化し、確認できる会話パターンの要約と参考意見を提供します。",
          "すべての結果画面に、AIが生成した内容であることを示すラベルを表示します。",
        ],
      },
      {
        title: "結果の限界",
        paragraphs: [
          "ウサギは、相手の実際の感情、意図、好意、性格、性的指向、または関係の真偽を確認・保証するものではありません。",
          "結果は、メッセージ数、質問、会話の流れなど、確認できるパターンをもとにした参考情報です。医療・法律・金融・心理診断などの専門的な助言に代わるものではありません。",
        ],
      },
      {
        title: "会話と個人情報",
        paragraphs: [
          "利用する権限のある会話だけを入力してください。身分証番号、電話番号、住所、口座番号、健康情報などの機微な個人情報は隠してからアップロードしてください。",
          "入力内容と結果は、現在のブラウザセッションに一時保存される場合があります。同一リクエストの重複処理を減らすため、分析結果がサーバーに一定時間だけ一時キャッシュされる場合があります。",
        ],
      },
      {
        title: "サービス範囲",
        paragraphs: [
          "ウサギは、アプリ内で会話パターン分析を提供します。金融・投資助言、医療診断、ギャンブル、暗号資産取引、外部アプリのインストール誘導は提供しません。",
        ],
      },
    ],
    notice: "サービスを利用すると、上記の内容を確認したものとみなされます。大切な関係の判断では、AIの結果よりも実際の会話と当事者同士の直接的なコミュニケーションを優先してください。",
    back: "ホームに戻る",
  },
  zh: {
    eyebrow: "服务说明",
    title: "AI 分析与数据处理说明",
    sections: [
      {
        title: "生成式 AI 的使用",
        paragraphs: [
          "Usagi 使用生成式 AI 整理您输入或上传的对话，并根据可观察到的对话模式提供摘要和参考意见。",
          "每个结果页面都会显示标签，说明该内容由 AI 生成。",
        ],
      },
      {
        title: "结果的局限",
        paragraphs: [
          "Usagi 无法确认或保证对方真实的感受、意图、好感、性格、性取向或关系性质。",
          "结果仅根据消息数量、提问和对话节奏等可观察模式生成，不能替代医疗、法律、金融、心理诊断或其他专业建议。",
        ],
      },
      {
        title: "对话与个人信息",
        paragraphs: [
          "请只提交您有权使用的对话。上传前请遮挡身份证号码、电话号码、地址、银行账户和健康信息等敏感个人信息。",
          "输入内容和结果可能会临时保存在当前浏览器会话中。为减少同一请求的重复处理成本，分析结果也可能在服务器上限时缓存。",
        ],
      },
      {
        title: "服务范围",
        paragraphs: [
          "Usagi 在应用内提供对话模式分析，不提供金融或投资建议、医疗诊断、赌博、加密货币交易，也不会诱导安装其他应用。",
        ],
      },
    ],
    notice: "使用本服务即表示您已了解上述内容。对于重要的关系判断，请优先考虑真实对话和当事人之间的直接沟通，而不是 AI 生成的结果。",
    back: "返回首页",
  },
};

export default function PolicyPage() {
  const { locale } = useLocale();
  const copy = COPY[locale];

  return (
    <main className="shell">
      <div className="mobile-frame policy-page">
        <Brand />
        <div className="eyebrow">{copy.eyebrow}</div>
        <h1 className="section-title">{copy.title}</h1>

        {copy.sections.map((section) => (
          <section className="policy-section" key={section.title}>
            <h2>{section.title}</h2>
            {section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
          </section>
        ))}

        <div className="notice">{copy.notice}</div>
        <ButtonLink href="/" variant="primary" fullWidth>{copy.back}</ButtonLink>
      </div>
    </main>
  );
}
